Try harder to push keys into the pykmip server
A recent bring-up failed at execute[add key] with

    ConnectionRefusedError: [Errno 111] Connection refused

presumably because the pykmip-server hadn't finished starting up.

Now, catch that specific error, sleep for a bit, and try again.